name: Update Release with Latest Tag

on:
  push:
    branches:
      - main
    # Можно добавить фильтрацию по конкретным путям, если нужно обновлять релиз только при изменении конкретных файлов или директорий
    # paths:
    #   - '**/*.js'
    #   - '**/*.py'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Проверка репозитория и установка зависимостей
      - name: Checkout repository
        uses: actions/checkout@v4

      # Убедимся, что у нас актуальные зависимости и ветка main
      - name: Set up Git
        run: |
          git fetch --tags
          git checkout main

      # Создаём zip архив из репозитория без директории .github
      - name: Create ZIP archive excluding .github/workflows
        run: |
          zip -r release.zip . -x ".github/workflows/*"

      # Создаём новый релиз или обновляем существующий с тегом latest
      - name: Upload release with latest tag
        uses: softprops/action-gh-release@v1
        with:
          files: Boot-Anima.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
