name: Update Release

on:
  workflow_dispatch: # Это позволяет запускать workflow вручную

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create a ZIP archive excluding .github and .git
        run: |
          zip -r Boot-Anima.zip . -x ".git/*" ".github/*"

      - name: Upload the ZIP archive to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Boot-Anima.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Release with 'latest' tag
        run: |
          release_id=$(gh release view latest --json id -q ".id" || echo "")
          if [ -z "$release_id" ]; then
            echo "Creating new release with tag 'latest'"
            gh release create latest Boot-Anima.zip --title "Latest Release"
          else
            echo "Updating existing release with tag 'latest'"
            gh release upload latest Boot-Anima.zip
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
