#!/bin/bash

# Убедитесь, что вы находитесь в корне репозитория
REPO_DIR=$(pwd)
TAG="latest"
ZIP_NAME="Boot-Anima.zip"

# Убедитесь, что тег уже существует
git fetch --tags
if ! git rev-parse "$TAG" >/dev/null 2>&1; then
  echo "Ошибка: тег $TAG не найден в репозитории."
  exit 1
fi

# Создание списка файлов для архива
# Исключаем .git и .github
EXCLUDE_LIST="--exclude=.git --exclude=.github"

# Создаем архив
echo "Создаю архив $ZIP_NAME..."
zip -r "$ZIP_NAME" . $EXCLUDE_LIST

# Публикуем релиз на GitHub с уже существующим тегом latest
echo "Публикую релиз с тегом $TAG..."

# Получите доступ к GitHub API с токеном авторизации (замените YOUR_TOKEN на ваш персональный токен)
GITHUB_TOKEN="YOUR_TOKEN"
REPO="user/repo"  # Укажите свой репозиторий, например user/repo

# Создаем новый релиз с тегом "latest"
RELEASE_RESPONSE=$(curl -s -X POST "https://api.github.com/repos/$REPO/releases" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -d @- <<EOF
{
  "tag_name": "$TAG",
  "name": "Release $TAG",
  "body": "Обновление релиза с тегом $TAG",
  "draft": false,
  "prerelease": false
}
EOF
)

# Получаем URL для загрузки
UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | jq -r .upload_url | sed 's/{?name,label}//')

# Загружаем zip архив в релиз
echo "Загружаю архив $ZIP_NAME..."
curl -s -X POST "$UPLOAD_URL" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/zip" \
  --data-binary @"$ZIP_NAME"

echo "Релиз обновлен успешно."
