name: Create and Upload ZIP Archive

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      uses: actions/setup-git@v2

    - name: Create ZIP archive
      run: |
        zip -r Boot-anima.zip ./*

    - name: Create and push a new tag
      run: |
        TAG_NAME="latest"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: Boot-anima.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
