name: Release

on:
  push:
    tags:
      - 'latest*'  # Срабатывает при пуше тега

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (для использования для скрипта, если нужен)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create zip archive
        run: |
          mkdir output
          zip -r output/Boot-Anima.zip .  # Архивирует текущую директорию

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: output/my-archive.zip  # Указание на файл для загрузки
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Автоматически передает токен для аутентификации
