name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout репозитория
    - name: Checkout repository
      uses: actions/checkout@v2

    # Шаг 2: Устанавливаем необходимые инструменты (zip, jq)
    - name: Set up tools
      run: |
        sudo apt-get install zip jq

    # Шаг 3: Читаем версию из файла module.prop
    - name: Read version from module.prop
      id: version
      run: |
        version=$(grep -oP '^version=\K.+' module.prop)
        echo "version=$version" >> $GITHUB_ENV

    # Шаг 4: Создание архива, исключая папку .github/workflows
    - name: Create ZIP archive
      run: |
        zip -r Boot-Anima.zip . -x ".github/*"

    # Шаг 5: Получаем GitHub токен для публикации
    - name: Get the GitHub token
      id: get_token
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    # Шаг 6: Загрузка архива в GitHub Releases
    - name: Upload ZIP to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        files: Boot-Anima.zip
        tag: latest
        release_name: "Boot-Anima ${VERSION}"
        body: |
          Version: ${{ env.version }}
          Description: Just put [bootanimation.zip] into this script.
